### ISSUE TITLE
Caching surveyApi for translation

### ISSUE THREAD

**Issue by zenyr** [StateOfJS/StateOfJS-2019#47]
Hello, I'm trying to set up a 🇰🇷 Korean translation base for SoJS 2019. But the remote GQL queries are taking too long and they're constantly invalidated on every local file changes. I think this method might be wasteful as more translators jump in, or this might be my misunderstanding.

So the issue in short:

- Initial `surveyApi` fetches are repeated for every languages.
- Any i18n changes (`.md` files inside `/translations/` directory) will invalidate `surveyApi` and refetch every documents, everytime.
- `write out require` steps are repeated almost indefinitely, requiring us to restart the `dev` server on every change

As a vanilla react developer I'm not very familiar with current gql setup at the moment but I'm very much willing to dive into this. Can you share your thoughts?

**Comment by SachaG** [comment]
I don't think changing the `.md` files has anything to do with the survey API? I think in this case it might just be Gatsby's build process that's a bit slow. It's hard to tell exactly how everything interacts though, I guess in the future especially if we internationalize the API it might start to take a really long time to build the site for every language…

I don't have a good solution at this time besides hope for better Gatsby support for dynamic queries, sorry…
