### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfJS-2019#8]
Leave a comment/subscribe to this thread if you'd like to help us translate the 2019 results in your own language. 

---

You can find an explanation of the translation workflow here: https://medium.com/@sachagreif/help-us-translate-the-state-of-javascript-2018-survey-results-1488efa525c1

**Comment by zenyr** [comment]
I'm interested in translating into Korean. 👍 Ping me!

**Comment by jaideepghosh** [comment]
I’d like to contribute in translation from English (en-us) to Hindi (hi)

**Comment by ahmetkuslular** [comment]
I can help you with Turkish. 🇹🇷

**Comment by sandrooco** [comment]
I'd like to help with German.  Maybe not the full translation as I'm quite busy but proof reading should be possible.

**Comment by jothy1023** [comment]
Would love to help with simplified Chinese. :-P 🇨🇳

**Comment by polettoweb** [comment]
I can help with Italian

**Comment by augustinreille** [comment]
Can do this for French 🇫🇷

**Comment by Neko250** [comment]
Hi there 👋 I can translate it to Spanish (Spain). Let me know if you're interested !

**Comment by IsraelOrtuno** [comment]
I could help with Spanish too 🇪🇸

**Comment by slumbering** [comment]
Can help with French :) <g-emoji class="g-emoji" alias="fr" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f1eb-1f1f7.png">🇫🇷</g-emoji>

**Comment by kieryk123** [comment]
I would be a pleasure to help with Polish 🇵🇱 :)

**Comment by Stephan972** [comment]
Can help for proof reading in French :fr:

**Comment by Jonur** [comment]
I am interested in translating the survey to Greek 🇬🇷 🇨🇾 . Let me know! 👍

**Comment by Fercas123** [comment]
I would be happy to help if there is need for any more Spanish translators/ proof readers.

**Comment by ignaciomartinelias** [comment]
Happy to help translate in spanish as well

**Comment by arcdelta** [comment]
I would love to help with translating to Russian! 🇷🇺

**Comment by furagu** [comment]
Would be happy to help with the Russian translation as well 🇷🇺

**Comment by lucassmuller** [comment]
I can help with Brazilian Portuguese :)

**Comment by marceloemanoel** [comment]
I can also help with Brazilian Portuguese :)

**Comment by abdelbk** [comment]
I can help with Arabic

**Comment by EdwinBetanc0urt** [comment]
I could help with the Spanish translation :es:

**Comment by impodracer** [comment]
I can help with Korean translation! :kr: :)

**Comment by iaurg** [comment]
I can help with Brazilian Portuguese translation! 🇧🇷

**Comment by ybiquitous** [comment]
I can help with Japanese translation! 🇯🇵

**Comment by paulocoghi** [comment]
Brazilian Portuguese here as well! :brazil:

**Comment by Ibochkarev** [comment]
> I would love to help with translating to Russian!

I can also help with the translation into Russian

**Comment by jjyepez** [comment]
I can help with the spanish (latam) version.

**Comment by niconj** [comment]
I could help with Spanish

**Comment by marcelnakamine** [comment]
I can also help with Brazilian Portuguese :) 🇧🇷

**Comment by S1ngS1ng** [comment]
I'd like to help with Chinese 🇨🇳

**Comment by santimendoza** [comment]
I'd like to help with Spanish 🇨🇴🇪🇸

**Comment by zubairabaziz** [comment]
I can help with Malay :flag-my:

**Comment by luix30182** [comment]
I can help with Spanish (latam)

**Comment by pedrosouza** [comment]
I can help with Brazilian Portuguese too! 🇧🇷🇧🇷🇧🇷

**Comment by Abilay99** [comment]
Пожалуйста переводите на русском 🇷🇺

**Comment by seognil** [comment]
I'd like to help with Chinese 🇨🇳

**Comment by Myugen** [comment]
I can help with the Spanish translation too 🇮🇨.

**Comment by Rejpal** [comment]
I'd like to help with translation to Czech :czech_republic:

**Comment by deeborges** [comment]
Eu posso ajudar com a tradução do português do Brasil! Brasil

**Comment by dennybiasiolli** [comment]
I can help with Italian translations 🇮🇹

**Comment by karol-krzeminski** [comment]
@kieryk123 and I could help with Polish 🇵🇱

**Comment by YosiLeibman** [comment]
I can help with Hebrew translations

**Comment by SachaG** [comment]
This is great, thanks to everybody for volunteeting! I've updated the translation instructions for this year's codebase, you can find them here: https://medium.com/@sachagreif/help-us-translate-the-state-of-javascript-2018-survey-results-1488efa525c1

If you have specific questions feel free to open new issues rather than add to this one, just to avoid notifying everybody else.

**Comment by TheDarkPirate** [comment]
Happy to help in Turkish 🇹🇷

**Comment by manusanchev** [comment]
i'd like to help with spanish too

**Comment by paoru5444** [comment]
I can help with pt-br Portuguese

**Comment by superzoey** [comment]
I'd like to help with Chinese 🇨🇳

**Comment by saranron** [comment]
I’d like to help with Thai translation :) 🇹🇭

**Comment by MedElHeni** [comment]
I'd like to help with Arabic AR

**Comment by medelmourabite** [comment]
I'd like to help with arabic

**Comment by javiBertos** [comment]
I could help with the Spanish translations also 🇪🇸

**Comment by tw1ttt3r** [comment]
I can help in latam translation!!!!  🇲🇽

**Comment by r3sMetz** [comment]
German translation started at #76 🇩🇪

**Comment by martinstefek** [comment]
I would love to help with translation into Slovak 🇸🇰

**Comment by luisfrocha** [comment]
I can help with Spanish, too.

**Comment by EmaSuriano** [comment]
Happy to help with Spanish 🇪🇸🇦🇷

**Comment by gemanepa** [comment]
Happy to help with latin american spanish

**Comment by Riccardo-Andreatta** [comment]
I can help with Italian 🇮🇹 translation as the one that is online now is not really understandable and fluent.

**Comment by davjvo** [comment]
Could help with Spanish too 🇪🇸

**Comment by casvaniersel** [comment]
I can help with Dutch! 🇾🇪

**Comment by anediaz** [comment]
Hello, I'd be happy to translate it in Basque if you're interested 😊😊
Feel free to contact me !

**Comment by wemf** [comment]
I would like to help to translate to spanish 🇪🇸

**Comment by amirhosseinrahmati** [comment]
Strongly eager to translate to Persian.

**Comment by dominguezcelada** [comment]
If you need help translating to Spanish and/or Catalan, I can help

**Comment by sk8Guerra** [comment]
I could also help to translate to Spanish. 🇬🇹🇪🇸

**Comment by romanfedyshyn** [comment]
Can help with Ukrainian 🇺🇦

**Comment by jgalianoz** [comment]
I can help with Spanish, too. 🇪🇸 🇻🇪

**Comment by wemf** [comment]
> I can help with Spanish, too.

Hello @jgalianoz, I'm from Venezuela too, check out my pull request for Spanish translation

**Comment by jgalianoz** [comment]
Hello @wemf, nice to mee too. What would the correct path for contributing to the Spanish translation?  Should I do a fork of your fork?

**Comment by maugares** [comment]
I can help translating to Spanish

**Comment by tnzk** [comment]
> I can help with Japanese translation! 🇯🇵

@ybiquitous Hi, have you started working on this? If so, I would like to join it. Could you give me an invitation?

**Comment by ybiquitous** [comment]
@tnzk sorry, I do not start yet.

**Comment by Logicus03** [comment]
I can help with Spanish version.

**Comment by acroooo** [comment]
I could help with Spanish! :es:

**Comment by Carolain** [comment]
Hi, will you notify anything here when it's time to start translating 2020? I'd like to help with Spanish.

**Comment by Fabezio** [comment]
Certainly, for french language :fr: With pleasure :grinning:

**Comment by SachaG** [comment]
> Hi, will you notify anything here when it's time to start translating 2020? I'd like to help with Spanish.

Do you mean translate for 2021? Yes, I'll post in this thread again. But even before then we'll have new strings to translate for the State of CSS 2020 results site, and then the 2020 State of JS survey and results as well! 

EDIT: Oh sorry I didn't see this was the thread for 2019 haha… The 2020 thread is here: https://github.com/StateOfJS/StateOfCSS-2020/issues/2

This confusion made me realize we need to centralize all these threads, I'll work on this later.

**Comment by SachaG** [comment]
See here for future discussion about translation work: https://github.com/StateOfJS/Translations/issues/1
